#### Pandas 패키지의 소개

#### 시리즈 클래스
#### 시리즈 생성

In [1]:
import pandas as pd
import numpy as np

In [2]:
s = pd.Series([9904312, 3448737, 2890451, 2466052], index=["서울", "부산", "인천", "대구"])

In [3]:
s

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [4]:
pd.Series(range(10, 14))

0    10
1    11
2    12
3    13
dtype: int64

In [5]:
s.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [6]:
s.values

array([9904312, 3448737, 2890451, 2466052], dtype=int64)

In [7]:
s.name = "인구"
s.index.name = "도시"

In [8]:
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

#### 시리즈 연산

In [9]:
s / 1000000

도시
서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
Name: 인구, dtype: float64

In [10]:
s[1], s["부산"]

(3448737, 3448737)

In [11]:
s[3], s["대구"]

(2466052, 2466052)

In [12]:
s[[0,3,1]]

도시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

In [13]:
s[["서울","대구","부산"]]

도시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

In [14]:
s[(250e4 < s) & (s < 500e4)]

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [15]:
s[1:3]

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [16]:
s["부산":"대구"]

도시
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

#### 시리즈와 딕셔너리 자료형

In [17]:
"서울" in s

True

In [18]:
"대전" in s

False

In [19]:
for k,v in s.items():
    print("%s = %d" % (k,v))

서울 = 9904312
부산 = 3448737
인천 = 2890451
대구 = 2466052


In [20]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158})
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [21]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158},
               index=["부산", "서울", "인천", "대전"])
s2

부산    3393191
서울    9631482
인천    2632035
대전    1490158
dtype: int64

#### 인덱스 기반 연산

In [22]:
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [23]:
s2

부산    3393191
서울    9631482
인천    2632035
대전    1490158
dtype: int64

In [24]:
ds = s - s2 #대응하는 인덱스 값을 뺌
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [25]:
s.values - s2.values #순서대로 뺌

array([ 6511121, -6182745,   258416,   975894], dtype=int64)

In [26]:
ds.notnull()

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool

In [27]:
ds[ds.notnull()]

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [28]:
rs = (s-s2) / s2 * 100
rs = rs[rs.notnull()]
rs

부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64

#### 데이터의 갱신, 추가, 삭제

In [29]:
rs["부산"] = 1.63
rs

부산    1.630000
서울    2.832690
인천    9.818107
dtype: float64

In [30]:
rs["대구"] = 1.41
rs

부산    1.630000
서울    2.832690
인천    9.818107
대구    1.410000
dtype: float64

In [31]:
del rs["서울"]

In [32]:
rs

부산    1.630000
인천    9.818107
대구    1.410000
dtype: float64

#### 연습 문제 1

In [33]:
s1 = pd.Series({"월요일":0,"화요일":3,"수요일":2,"목요일":2,"금요일":2})

In [34]:
s2 = pd.Series({"월요일":2,"화요일":1,"수요일":1,"목요일":1,"금요일":1,"토요일":1})

In [35]:
s2

월요일    2
화요일    1
수요일    1
목요일    1
금요일    1
토요일    1
dtype: int64

In [36]:
s1.index.name = "요일"
s2.index.name = "요일"

In [37]:
s1

요일
월요일    0
화요일    3
수요일    2
목요일    2
금요일    2
dtype: int64

In [38]:
"토요일" in s1

False

In [39]:
"토요일" in s2

True

In [40]:
s1.values

array([0, 3, 2, 2, 2], dtype=int64)

In [41]:
s2.values

array([2, 1, 1, 1, 1, 1], dtype=int64)

In [42]:
ns = s1+s2

In [43]:
s1-s2

요일
금요일    1.0
목요일    1.0
수요일    1.0
월요일   -2.0
토요일    NaN
화요일    2.0
dtype: float64

In [44]:
s1*s2

요일
금요일    2.0
목요일    2.0
수요일    2.0
월요일    0.0
토요일    NaN
화요일    3.0
dtype: float64

In [45]:
s1*s2

요일
금요일    2.0
목요일    2.0
수요일    2.0
월요일    0.0
토요일    NaN
화요일    3.0
dtype: float64

In [46]:
ns[ns.notnull()]

요일
금요일    3.0
목요일    3.0
수요일    3.0
월요일    2.0
화요일    4.0
dtype: float64

#### 데이터프레임 클래스

In [47]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}

index = ["서울", "부산", "인천", "대구"]
columns = ["지역","2000","2005","2010","2015","2010-2015 증가율"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2000     2005     2010     2015  2010-2015 증가율
서울  수도권  9853972  9762546  9631482  9904312         0.0283
부산  경상권  3655437  3512547  3393191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982
대구  경상권  2473990  2456016  2431774  2466052         0.0141

In [48]:
df.values

array([['수도권', 9853972, 9762546, 9631482, 9904312, 0.0283],
       ['경상권', 3655437, 3512547, 3393191, 3448737, 0.0163],
       ['수도권', 2466338, 2517680, 2632035, 2890451, 0.0982],
       ['경상권', 2473990, 2456016, 2431774, 2466052, 0.0141]], dtype=object)

In [49]:
df.columns

Index(['지역', '2000', '2005', '2010', '2015', '2010-2015 증가율'], dtype='object')

In [50]:
df.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [51]:
df.index.name = "도시"
df.columns.name = "특성"
df

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312         0.0283
부산  경상권  3655437  3512547  3393191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982
대구  경상권  2473990  2456016  2431774  2466052         0.0141

#### 연습 문제 2

In [52]:
data = {
    "요일": ["월요일", "화요일", "수요일", "목요일","금요일"],
    "번역 여부": [True, False, False, False, True],
    "코딩 장수": [0, 3.5, 1.5, 6, 2],
    "퇴근시간": [np.NaN, "17:00", "22:00", "21:30", "22:00"],
}
index = ["20일", "21일", "22일", "23일", "24일"]
columns =  ["요일","번역 여부","코딩 장수","퇴근시간"]
df1 = pd.DataFrame(data, index = index, columns = columns)

In [53]:
df1

요일  번역 여부  코딩 장수   퇴근시간
20일  월요일   True    0.0    NaN
21일  화요일  False    3.5  17:00
22일  수요일  False    1.5  22:00
23일  목요일  False    6.0  21:30
24일  금요일   True    2.0  22:00

In [54]:
df1.columns

Index(['요일', '번역 여부', '코딩 장수', '퇴근시간'], dtype='object')

In [55]:
df1.index

Index(['20일', '21일', '22일', '23일', '24일'], dtype='object')

In [56]:
df1.columns.name = "날짜"
df1

날짜    요일  번역 여부  코딩 장수   퇴근시간
20일  월요일   True    0.0    NaN
21일  화요일  False    3.5  17:00
22일  수요일  False    1.5  22:00
23일  목요일  False    6.0  21:30
24일  금요일   True    2.0  22:00

In [57]:
df1.T

20일    21일    22일    23일    24일
날짜                                     
요일      월요일    화요일    수요일    목요일    금요일
번역 여부  True  False  False  False   True
코딩 장수     0    3.5    1.5      6      2
퇴근시간    NaN  17:00  22:00  21:30  22:00

#### 열 데이터의 갱신, 추가, 삭제

In [58]:
df

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312         0.0283
부산  경상권  3655437  3512547  3393191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982
대구  경상권  2473990  2456016  2431774  2466052         0.0141

In [59]:
df["2010-2015 증가율"] = df["2010-2015 증가율"] * 100
df

특성   지역     2000     2005     2010     2015  2010-2015 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312           2.83
부산  경상권  3655437  3512547  3393191  3448737           1.63
인천  수도권  2466338  2517680  2632035  2890451           9.82
대구  경상권  2473990  2456016  2431774  2466052           1.41

In [60]:
df["2005-2010 증가율"] = round((df['2010'] - df['2005']) / df["2005"] * 100, 2)

In [61]:
df

특성   지역     2000     2005     2010     2015  2010-2015 증가율  2005-2010 증가율
도시                                                                       
서울  수도권  9853972  9762546  9631482  9904312           2.83          -1.34
부산  경상권  3655437  3512547  3393191  3448737           1.63          -3.40
인천  수도권  2466338  2517680  2632035  2890451           9.82           4.54
대구  경상권  2473990  2456016  2431774  2466052           1.41          -0.99

In [62]:
del df["2010-2015 증가율"]
df

특성   지역     2000     2005     2010     2015  2005-2010 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312          -1.34
부산  경상권  3655437  3512547  3393191  3448737          -3.40
인천  수도권  2466338  2517680  2632035  2890451           4.54
대구  경상권  2473990  2456016  2431774  2466052          -0.99

#### 열 인덱싱

In [63]:
df["지역"]

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [64]:
df[["2010", "2015"]]

특성     2010     2015
도시                  
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

In [65]:
df["2010"]

도시
서울    9631482
부산    3393191
인천    2632035
대구    2431774
Name: 2010, dtype: int64

In [66]:
type(df["2010"])

pandas.core.series.Series

In [67]:
df[["2010"]]

특성     2010
도시         
서울  9631482
부산  3393191
인천  2632035
대구  2431774

In [68]:
type(df[["2010"]])

pandas.core.frame.DataFrame

In [69]:
df

특성   지역     2000     2005     2010     2015  2005-2010 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312          -1.34
부산  경상권  3655437  3512547  3393191  3448737          -3.40
인천  수도권  2466338  2517680  2632035  2890451           4.54
대구  경상권  2473990  2456016  2431774  2466052          -0.99

In [70]:
df.index

Index(['서울', '부산', '인천', '대구'], dtype='object', name='도시')

In [71]:
try:
    df[0]
except Exception as e:
    print(type(e))

<class 'KeyError'>


In [72]:
df2 = pd.DataFrame(np.arange(12).reshape(3, 4))
df2

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [73]:
df2[2]

0     2
1     6
2    10
Name: 2, dtype: int32

In [74]:
df2[[1, 2]]

1   2
0  1   2
1  5   6
2  9  10

#### 행 인덱싱

In [75]:
df[:1]

특성   지역     2000     2005     2010     2015  2005-2010 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312          -1.34

In [76]:
df[1:2]

특성   지역     2000     2005     2010     2015  2005-2010 증가율
도시                                                        
부산  경상권  3655437  3512547  3393191  3448737           -3.4

In [77]:
df[1:3]

특성   지역     2000     2005     2010     2015  2005-2010 증가율
도시                                                        
부산  경상권  3655437  3512547  3393191  3448737          -3.40
인천  수도권  2466338  2517680  2632035  2890451           4.54

In [78]:
df["서울":"부산"]

특성   지역     2000     2005     2010     2015  2005-2010 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312          -1.34
부산  경상권  3655437  3512547  3393191  3448737          -3.40

#### 개별 데이터 인덱싱

In [79]:
df

특성   지역     2000     2005     2010     2015  2005-2010 증가율
도시                                                        
서울  수도권  9853972  9762546  9631482  9904312          -1.34
부산  경상권  3655437  3512547  3393191  3448737          -3.40
인천  수도권  2466338  2517680  2632035  2890451           4.54
대구  경상권  2473990  2456016  2431774  2466052          -0.99

In [80]:
df["2015"]["서울"]

9904312

#### 연습 문제 3

In [81]:
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)

In [82]:
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [83]:
df[:4]

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [84]:
df["수학"]

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

In [85]:
type(df["수학"])

pandas.core.series.Series

In [86]:
df[["국어","영어"]]

국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  40

In [87]:
df["평균 점수"] = (df["국어"] + df["영어"] + df["수학"]) / 3

In [88]:
df

국어  영어  수학      평균 점수
춘향  80  90  90  86.666667
몽룡  90  70  60  73.333333
향단  70  60  80  70.000000
방자  30  40  70  46.666667

In [89]:
df["영어"]["방자"] = 80
df["평균 점수"] = (df["국어"] + df["영어"] + df["수학"]) / 3

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [90]:
df

국어  영어  수학      평균 점수
춘향  80  90  90  86.666667
몽룡  90  70  60  73.333333
향단  70  60  80  70.000000
방자  30  80  70  60.000000

In [91]:
df[:1]

국어  영어  수학      평균 점수
춘향  80  90  90  86.666667

In [92]:
df.T["향단"]

국어       70.0
영어       60.0
수학       80.0
평균 점수    70.0
Name: 향단, dtype: float64

In [93]:
type(df.T["향단"])

pandas.core.series.Series