#### 난수 발생과 카운팅

#### 시드 설정하기

In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [3]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [4]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [5]:
np.random.seed(0)

In [6]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [7]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [8]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

#### 데이터의 순서 바꾸기

In [9]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.random.shuffle(x)
x

array([3, 6, 4, 5, 2, 9, 7, 8, 1, 0])

#### 데이터 샘플링

In [11]:
np.random.choice(5,5, replace=False) #shuffle 명령과 같다

array([1, 4, 0, 3, 2])

In [12]:
np.random.choice(5,3, replace=False) #3개만 선택

array([2, 1, 3])

In [13]:
np.random.choice(5,10) #반복해서 10개 선택 replace=True

array([0, 4, 1, 4, 1, 2, 2, 0, 1, 1])

In [14]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])  # 선택 확률을 다르게 해서 10개 선택

array([0, 3, 3, 2, 2, 3, 3, 2, 0, 3], dtype=int64)

#### 난수 생성

In [15]:
np.random.rand(10)

array([0.95894927, 0.65279032, 0.63505887, 0.99529957, 0.58185033,
       0.41436859, 0.4746975 , 0.6235101 , 0.33800761, 0.67475232])

In [16]:
np.random.rand(3,5)

array([[0.31720174, 0.77834548, 0.94957105, 0.66252687, 0.01357164],
       [0.6228461 , 0.67365963, 0.971945  , 0.87819347, 0.50962438],
       [0.05571469, 0.45115921, 0.01998767, 0.44171092, 0.97958673]])

In [17]:
np.random.randn(10)

array([-0.30237513, -2.2244036 ,  0.72400636,  0.35900276,  1.07612104,
        0.19214083,  0.85292596,  0.01835718,  0.42830357,  0.99627783])

In [18]:
np.random.randn(3, 5)

array([[-0.49114966,  0.71267817,  1.11334035, -2.15367459, -0.41611148],
       [-1.07089699,  0.22113881, -1.12305712, -1.05075796,  1.01207905],
       [ 1.54371643, -0.40211489,  0.8647491 , -0.22686923,  0.81116027]])

In [19]:
np.random.randint(10, 20, size=10) #10~20사이 난수

array([10, 14, 13, 16, 19, 18, 10, 18, 15, 19])

In [20]:
np.random.randint(10, 20, size=(3, 5))

array([[10, 19, 16, 15, 13],
       [11, 18, 10, 14, 19],
       [16, 15, 17, 18, 18]])

#### 정수 데이터 카운팅

In [21]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [22]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [23]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [24]:
count

array([2, 2, 1], dtype=int64)

In [25]:
# unique()는 데이터 값이 나올 수 있음에도 불구하고 데이터가 하나도 없는 경우에는 정보를 주지 않는다.
# bincount에 minlength 인수를 설정하여 쓰는 것이 더 편리하다. 
# 0 부터 minlength - 1 까지의 숫자에 대해 각각 카운트를 한다

In [26]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6) 

array([0, 2, 3, 1, 0, 0], dtype=int64)