#### Numpy 배열

In [1]:
import numpy as np

#### 1차원 배열 만들기

In [2]:
ar = np.array([0,1,2,3,4,5,6,7,8,9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(ar)

numpy.ndarray

#### 벡터화 연산

In [4]:
data = [0,1,2,3,4,5,6,7,8,9]

In [5]:
answer = []
for di in data:
    answer.append(2*di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [6]:
x = np.array(data)

In [7]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
L = [0,1,2,3,4,5,6,7,8,9]
print(2*L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [10]:
a = np.array([1,2,3])
b = np.array([10,20,30])

In [11]:
2 * a + b

array([12, 24, 36])

In [12]:
a == 2

array([False,  True, False])

In [13]:
b > 10

array([False,  True,  True])

In [14]:
(a == 2) & (b > 10)

array([False,  True, False])

#### 2차원 배열 만들기

In [16]:
c = np.array([[0,1,2],[3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
len(c) #행의 개수

2

In [18]:
len(c[0]) #열의 개수

3

#### 연습 문제 4.1.1

In [20]:
x = np.array([[10,20,30,40],[50,60,70,80]])
x

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

#### 3차원 배열 만들기

In [22]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array

NameError: name 'ᄋ' is not defined

In [23]:
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [24]:
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

#### 배열의 차원과 크기 알아내기

In [25]:
a = np.array([1, 2, 3])
print(a.ndim) #배열의 차원
print(a.shape) #배열의 크기

1
(3,)


In [26]:
c = np.array([[0, 1, 2], [3, 4, 5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [27]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


#### 배열의 인덱싱

In [28]:
a = np.array([0, 1, 2, 3, 4])

In [29]:
a[2]

2

In [31]:
a[-1]

4

In [32]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [33]:
a[0, 0]  # 첫번째 행의 첫번째 열

0

In [34]:
a[0, 1]  # 첫번째 행의 두번째 열

1

In [36]:
a[-1, -1]  # 마지막 행의 마지막 열

5

#### 배열 슬라이싱

In [41]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [38]:
a[0, :]  # 첫번째 행 전체

array([0, 1, 2, 3])

In [39]:
a[:, 1]  # 두번째 열 전체

array([1, 5])

In [40]:
a[1, 1:]  # 두번째 행의 두번째 열부터 끝열까지

array([5, 6, 7])

In [42]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

#### 연습 문제 4.1.2

In [43]:
m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])

In [45]:
print(m.ndim)
print(m.shape)

2
(3, 5)


In [48]:
m[1,2]

7

In [49]:
m[-1,-1]

14

In [53]:
m[1,1:3]

array([6, 7])

In [55]:
m[1:3,2]

array([ 7, 12])

In [58]:
m[:2,3:5]

array([[3, 4],
       [8, 9]])

#### 배열 인덱싱

In [59]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [60]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [62]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [63]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [64]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [65]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [67]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

#### 연습 문제 4.1.3

In [70]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [71]:
print(x.ndim)
print(x.shape)

1
(20,)


In [76]:
x % 3 == 0

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False])

In [77]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [78]:
x % 4 == 1

array([ True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False])

In [79]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [80]:
(x % 3 == 0) & (x % 4 == 1)

array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [81]:
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])