#### 배열의 연산

#### 벡터화 연산

In [2]:
import numpy as np

In [3]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [5]:
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

In [6]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [8]:
z = x + y

In [9]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [10]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [11]:
a == b

array([False,  True, False,  True])

In [12]:
a >= b

array([False,  True,  True,  True])

In [13]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [14]:
np.all(a == b) #열의 모든 원소가 다 같은지 알고 싶을때

False

In [15]:
np.all(a == c)

True

In [16]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [17]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [18]:
10 ** a

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [19]:
np.log(a+1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

#### 스칼라와 벡터/행렬의 곱셈

In [20]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [23]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

#### 브로드캐스팅 Broadcasting

In [25]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [26]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [27]:
x + y

array([1, 2, 3, 4, 5])

In [28]:
x + 1

array([1, 2, 3, 4, 5])

In [29]:
x = np.vstack([range(7)[i:i + 3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [30]:
y = np.arange(5)[:, np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [31]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [32]:
y = np.arange(3)
y

array([0, 1, 2])

In [33]:
x + y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

#### 차원 축소 연산

In [34]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [36]:
np.sum(x)

10

In [37]:
x.sum()

10

In [38]:
x = np.array([1, 3, 2])
x

array([1, 3, 2])

In [40]:
x.min()

1

In [41]:
x.max()

3

In [42]:
x.argmin()  # 최솟값의 위치

0

In [43]:
x.argmax()  # 최댓값의 위치

1

In [44]:
x = np.array([1, 2, 3, 1])

In [46]:
x.mean()

1.75

In [47]:
np.median(x)

1.5

In [48]:
np.all([True, True, False])

False

In [49]:
np.any([True, True, False])

True

In [50]:
a = np.zeros((100, 100), dtype=np.int)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [51]:
np.any(a != 0)

False

In [52]:
np.all(a == a)

True

In [53]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

In [54]:
((a <= b) & (b <= c)).all()

True

In [55]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [56]:
x.sum()

6

In [57]:
x.sum(axis=0)   # 열 합계

array([3, 3])

In [58]:
x.sum(axis=1)   # 행 합계

array([2, 4])

#### 연습 문제 4.1.5

In [60]:
x = np.arange(30).reshape(5,6)

In [61]:
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [62]:
x.max()

29

In [63]:
x.argmax()

29

In [64]:
x.sum()

435

In [69]:
x.sum(axis=1)

array([ 15,  51,  87, 123, 159])

In [68]:
x.mean(axis=0)

array([12., 13., 14., 15., 16., 17.])

#### 정렬

In [72]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [73]:
np.sort(a)  #각각의 열을 따로따로 정렬 axis=1 OR -1

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [74]:
np.sort(a, axis=0) #각각의 행을 따로따로 정렬

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [75]:
a.sort(axis=1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [76]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a) #자료를 정렬하는 것이 아니라 순서만 알고 싶다면
j

array([2, 3, 1, 0], dtype=int64)

In [77]:
a[j]

array([12, 25, 38, 42])

In [78]:
np.sort(a)

array([12, 25, 38, 42])

#### 연습 문제 4.1.6

In [113]:
x = np.array([[  1,    2,    3,    4],
              [ 46,   99,  100,   71],
              [ 81,   59,   90,  100]])

In [114]:
x

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [119]:
np.sort(x) #각 행마다 정렬

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])